dependencies: |
  ecmwf/ecbuild
  Deutsches-Klimarechenzentrum/libaec@refs/tags/v1.1.6
  ecmwf/eccodes
  ecmwf/eckit
  ecmwf/metkit
dependency_branch: develop
cmake_options: -DENABLE_MEMFS=ON -DENABLE_DUMMY_DAOS=ON -DENABLE_FAMFDB=ON
parallelism_factor: 8
