dependencies: |
  ecmwf/ecbuild@develop
  MathisRosenhauer/libaec@refs/tags/v1.1.3
  ecmwf/eccodes@develop
  ecmwf/eckit@feature/ECKIT-635_fam-backend-map
  ecmwf/odc@develop
  ecmwf/metkit@develop
cmake_options: -DENABLE_DUMMY_DAOS=ON -DENABLE_FAMFDB=ON
parallelism_factor: 8
