version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

  commands:
    - mkdir -p html
    - echo "<!DOCTYPE html><html><head><title>Hello</title></head><body><h1>Hello, World!</h1></body></html>" > html/index.html

  output:
    html: html
