version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  commands:
    - pip install -r docs/requirements.txt
    - DOCBUILD_OUTPUT=docs_out ./docs/build_docs.sh
    - mkdir -p $READTHEDOCS_OUTPUT/html
    - mv docs_out/sphinx/* $READTHEDOCS_OUTPUT/html

