# This is needed to resolve the correct paths in test module for pytest
# Otherwise the test folder (which carry the same names as the modules) clash
# due to the prepending nature of pytests import
[pytest]
addopts = ["--import-mode=importlib"]
