apiVersion: v1
kind: Service
metadata:
  name: caddy-service
spec:
  type: LoadBalancer # Or NodePort for simpler Minikube access
  selector:
    app: caddy
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
