// fdb_bridge.h - C++ bridge declarations for cxx
//
// This header declares wrapper types and shim functions that convert between
// the native FDB5 C++ API and cxx-compatible types.

#pragma once

#include "rust/cxx.h"

#include <memory>
#include <string>
#include <vector>

// Use shared eckit exception handler (auto-generated by bindman)
#include "eckit_exceptions.h"

// metkit-sys bridge — provides MarsRequestWrapper
#include "metkit-sys/src/lib.rs.h"

// eckit-sys bridge — provides DataHandleWrapper
#include "eckit-sys/src/lib.rs.h"

#include "fdb5/api/FDB.h"
#include "fdb5/api/helpers/ControlIterator.h"
#include "fdb5/message/MessageArchiver.h"
#include "fdb5/api/helpers/DumpIterator.h"
#include "fdb5/api/helpers/ListIterator.h"
#include "fdb5/api/helpers/PurgeIterator.h"
#include "fdb5/api/helpers/StatsIterator.h"
#include "fdb5/api/helpers/StatusIterator.h"
#include "fdb5/api/helpers/WipeIterator.h"

#include "eckit/io/DataHandle.h"

namespace fdb::ffi {

// Import MarsRequestWrapper from metkit-sys bridge (cross-crate ExternType)
using metkit_bridge::MarsRequestWrapper;

// Import DataHandleWrapper from eckit-sys bridge (cross-crate ExternType)
using eckit_bridge::DataHandleWrapper;

// ============================================================================
// Shared struct forward declarations (defined by cxx in generated code)
// ============================================================================

struct KeyValue;
struct KeyData;
struct ListElementData;
struct CompactListingData;
struct AxisEntry;
struct FdbStatsData;
struct DumpElementData;
struct StatusElementData;
struct WipeElementData;
struct PurgeElementData;
struct IndexStatsData;
struct DbStatsData;
struct StatsElementData;
struct ControlElementData;

// ============================================================================
// Wrapper classes for opaque C++ types
// ============================================================================

/// Wrapper around fdb5::FDB that can be passed through cxx.
class FdbHandle {
public:

    FdbHandle();
    explicit FdbHandle(const eckit_bridge::ConfigWrapper& config);
    FdbHandle(const eckit_bridge::ConfigWrapper& config, const eckit_bridge::ConfigWrapper& user_config);

    ~FdbHandle();

    // Non-copyable
    FdbHandle(const FdbHandle&) = delete;
    FdbHandle& operator=(const FdbHandle&) = delete;

    // Movable
    FdbHandle(FdbHandle&&) = default;
    FdbHandle& operator=(FdbHandle&&) = default;

    /// Access the underlying FDB instance.
    fdb5::FDB& inner() { return impl_; }
    const fdb5::FDB& inner() const { return impl_; }

    // -------------------------------------------------------------------------
    // Methods exposed to Rust via cxx
    // -------------------------------------------------------------------------

    /// Check if the FDB has unflushed data.
    bool dirty() const;

    /// Flush pending writes to disk.
    void flush();

    /// Get aggregate statistics.
    FdbStatsData stats() const;

    /// Check if a control identifier is enabled.
    bool enabled(fdb5::ControlIdentifier identifier) const;

    /// Get the FDB configuration ID.
    rust::String id() const;

    /// Get the FDB type name.
    rust::String name() const;

private:

    fdb5::FDB impl_;
};

/// Wrapper around fdb5::ListIterator.
class ListIteratorHandle {
public:

    explicit ListIteratorHandle(fdb5::ListIterator&& it);
    ~ListIteratorHandle();

    // Non-copyable
    ListIteratorHandle(const ListIteratorHandle&) = delete;
    ListIteratorHandle& operator=(const ListIteratorHandle&) = delete;

    // Movable
    ListIteratorHandle(ListIteratorHandle&&) = default;
    ListIteratorHandle& operator=(ListIteratorHandle&&) = default;

    // Methods exposed to Rust via cxx
    bool hasNext();
    ListElementData next();

    /// Access the underlying ListIterator (for read_list_iterator).
    fdb5::ListIterator& inner() { return impl_; }

private:

    fdb5::ListIterator impl_;
    fdb5::ListElement current_;
    bool has_current_ = false;
    bool exhausted_ = false;
};

/// Wrapper around fdb5::DumpIterator.
class DumpIteratorHandle {
public:

    explicit DumpIteratorHandle(fdb5::DumpIterator&& it);
    ~DumpIteratorHandle();

    DumpIteratorHandle(const DumpIteratorHandle&) = delete;
    DumpIteratorHandle& operator=(const DumpIteratorHandle&) = delete;
    DumpIteratorHandle(DumpIteratorHandle&&) = default;
    DumpIteratorHandle& operator=(DumpIteratorHandle&&) = default;

    // Methods exposed to Rust via cxx
    bool hasNext();
    DumpElementData next();

private:

    fdb5::DumpIterator impl_;
    fdb5::DumpElement current_;
    bool has_current_ = false;
    bool exhausted_ = false;
};

/// Wrapper around fdb5::StatusIterator.
class StatusIteratorHandle {
public:

    explicit StatusIteratorHandle(fdb5::StatusIterator&& it);
    ~StatusIteratorHandle();

    StatusIteratorHandle(const StatusIteratorHandle&) = delete;
    StatusIteratorHandle& operator=(const StatusIteratorHandle&) = delete;
    StatusIteratorHandle(StatusIteratorHandle&&) = default;
    StatusIteratorHandle& operator=(StatusIteratorHandle&&) = default;

    // Methods exposed to Rust via cxx
    bool hasNext();
    StatusElementData next();

private:

    fdb5::StatusIterator impl_;
    fdb5::StatusElement current_;
    bool has_current_ = false;
    bool exhausted_ = false;
};

/// Wrapper around fdb5::WipeIterator.
class WipeIteratorHandle {
public:

    explicit WipeIteratorHandle(fdb5::WipeIterator&& it);
    ~WipeIteratorHandle();

    WipeIteratorHandle(const WipeIteratorHandle&) = delete;
    WipeIteratorHandle& operator=(const WipeIteratorHandle&) = delete;
    WipeIteratorHandle(WipeIteratorHandle&&) = default;
    WipeIteratorHandle& operator=(WipeIteratorHandle&&) = default;

    // Methods exposed to Rust via cxx
    bool hasNext();
    WipeElementData next();

private:

    fdb5::WipeIterator impl_;
    fdb5::WipeElement current_;
    bool has_current_ = false;
    bool exhausted_ = false;
};

/// Wrapper around fdb5::PurgeIterator.
class PurgeIteratorHandle {
public:

    explicit PurgeIteratorHandle(fdb5::PurgeIterator&& it);
    ~PurgeIteratorHandle();

    PurgeIteratorHandle(const PurgeIteratorHandle&) = delete;
    PurgeIteratorHandle& operator=(const PurgeIteratorHandle&) = delete;
    PurgeIteratorHandle(PurgeIteratorHandle&&) = default;
    PurgeIteratorHandle& operator=(PurgeIteratorHandle&&) = default;

    // Methods exposed to Rust via cxx
    bool hasNext();
    PurgeElementData next();

private:

    fdb5::PurgeIterator impl_;
    fdb5::PurgeElement current_;
    bool has_current_ = false;
    bool exhausted_ = false;
};

/// Wrapper around fdb5::StatsIterator.
class StatsIteratorHandle {
public:

    explicit StatsIteratorHandle(fdb5::StatsIterator&& it);
    ~StatsIteratorHandle();

    StatsIteratorHandle(const StatsIteratorHandle&) = delete;
    StatsIteratorHandle& operator=(const StatsIteratorHandle&) = delete;
    StatsIteratorHandle(StatsIteratorHandle&&) = default;
    StatsIteratorHandle& operator=(StatsIteratorHandle&&) = default;

    // Methods exposed to Rust via cxx
    bool hasNext();
    StatsElementData next();

private:

    fdb5::StatsIterator impl_;
    fdb5::StatsElement current_;
    bool has_current_ = false;
    bool exhausted_ = false;
};

/// Wrapper around fdb5::ControlIterator.
class ControlIteratorHandle {
public:

    explicit ControlIteratorHandle(fdb5::ControlIterator&& it);
    ~ControlIteratorHandle();

    ControlIteratorHandle(const ControlIteratorHandle&) = delete;
    ControlIteratorHandle& operator=(const ControlIteratorHandle&) = delete;
    ControlIteratorHandle(ControlIteratorHandle&&) = default;
    ControlIteratorHandle& operator=(ControlIteratorHandle&&) = default;

    // Methods exposed to Rust via cxx
    bool hasNext();
    ControlElementData next();

private:

    fdb5::ControlIterator impl_;
    fdb5::ControlElement current_;
    bool has_current_ = false;
    bool exhausted_ = false;
};

// ============================================================================
// Initialization functions
// ============================================================================

/// Initialize the FDB library.
/// Must be called before any other FDB operations.
void fdb_init();

// ============================================================================
// Library metadata functions
// ============================================================================

/// Get the FDB library version string.
rust::String fdb_version();

/// Get the FDB git SHA1 hash.
rust::String fdb_git_sha1();

// ============================================================================
// Handle lifecycle functions
// ============================================================================

/// Create a new FDB handle with default configuration.
std::unique_ptr<FdbHandle> new_fdb();

/// Create a new FDB handle from an `eckit::Config`.
std::unique_ptr<FdbHandle> new_fdb_from_config(const eckit_bridge::ConfigWrapper& config);

/// Create a new FDB handle from an `eckit::Config` with user config overlay.
std::unique_ptr<FdbHandle> new_fdb_from_config_with_user_config(const eckit_bridge::ConfigWrapper& config,
                                                                const eckit_bridge::ConfigWrapper& user_config);

// ============================================================================
// Archive functions
// ============================================================================

/// Archive data with an explicit key.
void archive(FdbHandle& handle, const KeyData& key, rust::Slice<const uint8_t> data);

/// Archive raw GRIB data (key is extracted from the message).
void archive_raw(FdbHandle& handle, rust::Slice<const uint8_t> data);

// Forward declaration for the opaque Rust reader box used by
// `archive_reader`. Defined on the Rust side; cxx generates the symbol
// in the same namespace.
struct ReaderBox;

/// Archive raw GRIB data streamed from a Rust `std::io::Read` source.
/// Wraps the Rust reader in an `eckit::DataHandle` subclass and hands it
/// to `fdb5::FDB::archive(eckit::DataHandle&)`, which extracts the key
/// from each GRIB message as it streams.
void archive_reader(FdbHandle& handle, rust::Box<ReaderBox> reader);

/// Wraps `fdb5::MessageArchiver` — the class used by mars-client-cpp's
/// `FDBBase::archive`. The C++ ctor takes `(key, completeTransfers, verbose,
/// config)`; the wrapper exposes all four so the caller picks values
/// (mars-client-cpp uses an empty key + both flags `false`).
class MessageArchiverWrapper {
    fdb5::MessageArchiver archiver_;

public:

    MessageArchiverWrapper(const KeyData& key, bool complete_transfers, bool verbose,
                           const eckit_bridge::ConfigWrapper& config);

    /// `fdb5::MessageArchiver::archive(eckit::DataHandle&)` — returns bytes
    /// archived (eckit::Length cast to int64).
    int64_t archive(eckit_bridge::DataHandleWrapper& source);

    /// `fdb5::MessageArchiver::flush()`.
    void flush();
};

/// Construct a `MessageArchiverWrapper`.
std::unique_ptr<MessageArchiverWrapper> new_message_archiver(
    const KeyData& key, bool complete_transfers, bool verbose,
    const eckit_bridge::ConfigWrapper& config);

// ============================================================================
// Retrieve functions
// ============================================================================

/// Retrieve data matching a MarsRequest.
std::unique_ptr<DataHandleWrapper> retrieve(FdbHandle& handle, const metkit_bridge::MarsRequestWrapper& request);

// ============================================================================
// Read functions (by URI)
// ============================================================================

/// Read data from a single URI.
std::unique_ptr<DataHandleWrapper> read_uri(FdbHandle& handle, rust::Str uri);

/// Read data from a list of URIs.
std::unique_ptr<DataHandleWrapper> read_uris(FdbHandle& handle, const rust::Vec<rust::String>& uris,
                                             bool in_storage_order);

/// Read data from a list iterator (most efficient - avoids URI conversion).
std::unique_ptr<DataHandleWrapper> read_list_iterator(FdbHandle& handle, ListIteratorHandle& iterator,
                                                      bool in_storage_order);

// ============================================================================
// List functions
// ============================================================================

/// List data matching a request.
std::unique_ptr<ListIteratorHandle> list(FdbHandle& handle, const metkit_bridge::MarsRequestWrapper& request,
                                         bool deduplicate, int32_t level);

/// Drain a `ListIteratorHandle` via `fdb5::ListIterator::dumpCompact` and
/// return the aggregated MARS-request text plus the two counters.
CompactListingData list_iterator_dump_compact(ListIteratorHandle& iterator);

// ============================================================================
// Axes query functions
// ============================================================================

/// Get axes for a request.
rust::Vec<AxisEntry> axes(FdbHandle& handle, const metkit_bridge::MarsRequestWrapper& request, int32_t level);

// ============================================================================
// Dump functions
// ============================================================================

/// Dump database structure.
std::unique_ptr<DumpIteratorHandle> dump(FdbHandle& handle, const metkit_bridge::MarsRequestWrapper& request,
                                         bool simple);

// ============================================================================
// Status functions
// ============================================================================

/// Get database status.
std::unique_ptr<StatusIteratorHandle> status(FdbHandle& handle, const metkit_bridge::MarsRequestWrapper& request);

// ============================================================================
// Wipe functions
// ============================================================================

/// Wipe data matching a request.
std::unique_ptr<WipeIteratorHandle> wipe(FdbHandle& handle, const metkit_bridge::MarsRequestWrapper& request, bool doit,
                                         bool porcelain, bool unsafe_wipe_all);

// ============================================================================
// Purge functions
// ============================================================================

/// Purge duplicate data.
std::unique_ptr<PurgeIteratorHandle> purge(FdbHandle& handle, const metkit_bridge::MarsRequestWrapper& request,
                                           bool doit, bool porcelain);

// ============================================================================
// Stats functions
// ============================================================================

/// Get statistics iterator.
std::unique_ptr<StatsIteratorHandle> stats_iterator(FdbHandle& handle,
                                                    const metkit_bridge::MarsRequestWrapper& request);

// ============================================================================
// Control functions
// ============================================================================

/// Control database features.
std::unique_ptr<ControlIteratorHandle> control(FdbHandle& handle, const metkit_bridge::MarsRequestWrapper& request,
                                               fdb5::ControlAction action,
                                               rust::Slice<const fdb5::ControlIdentifier> identifiers);

// ============================================================================
// Callback registration functions
// ============================================================================

// Forward declare Rust callback box types
struct FlushCallbackBox;
struct ArchiveCallbackBox;

/// Register a flush callback.
void register_flush_callback(FdbHandle& handle, rust::Box<FlushCallbackBox> callback);

/// Register an archive callback.
void register_archive_callback(FdbHandle& handle, rust::Box<ArchiveCallbackBox> callback);

// ============================================================================
// Test functions (for verifying exception handling)
// ============================================================================

/// Test function that throws eckit::Exception
void test_throw_eckit_exception();

/// Test function that throws eckit::SeriousBug
void test_throw_eckit_serious_bug();

/// Test function that throws eckit::UserError
void test_throw_eckit_user_error();

/// Test function that throws std::runtime_error
void test_throw_std_exception();

/// Test function that throws an int (non-std::exception type)
void test_throw_int();

}  // namespace fdb::ffi
