[workspace]
resolver = "2"
members = ["crates/fdb-sys", "crates/fdb", "tools/fdb-hammer"]

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/ecmwf/fdb"
rust-version = "1.90"
readme = "README.md"
keywords = ["ecmwf", "weather", "meteorology", "grib", "climate"]
categories = ["science", "database"]

[workspace.dependencies]
# Internal
fdb-sys = { path = "crates/fdb-sys" }
fdb = { path = "crates/fdb" }

# Foundation crates
eckit-sys = { path = "../../rust-wrappers-playground/crates/eckit-sys", default-features = false }
eckit = { path = "../../rust-wrappers-playground/crates/eckit" }
metkit-sys = { path = "../../rust-wrappers-playground/crates/metkit-sys", default-features = false }
metkit = { path = "../../rust-wrappers-playground/crates/metkit" }
eccodes-sys = { path = "../../rust-wrappers-playground/crates/eccodes-sys", default-features = false }

# Build tools
bindman = { path = "../../bindman/bindman" }
bindman-build = { path = "../../bindman/bindman-build" }
bindman-utils = { path = "../../bindman/bindman-utils" }

# External
thiserror = "2"
cxx = "1.0"
cxx-build = "1.0"
parking_lot = "0.12"
tempfile = "3"
indexmap = "2"
