name: check-format

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

permissions:
  contents: read

jobs:
  checks:
    name: Run clang-format check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install clang-format-19
      run: |
        sudo add-apt-repository 'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main'
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
        sudo apt update
        sudo apt install clang-format-19

    - name: Run clang-format check
      run: |
        shopt -s globstar
        clang-format-19 -n --Werror --verbose **/*.h **/*.cc **/*.c
