name: ci

on:
  # Trigger the workflow manually
  workflow_dispatch: ~
  push: ~

jobs:
  hello-hpc:
    name: "This is a test"
    runs-on:
      - self-hosted
      - linux
      - hpc
    steps:
      - name: Checkout build-package-hpc@master
        uses: actions/checkout@v5
        with:
          repository: ecmwf/build-package-hpc
          ref: main
          path: build-package-hpc
          token: ${{ secrets.GH_REPO_READ_TOKEN }}
      - name: "LS"
        run: |
          echo $(pwd)
          ls -lah
          poetry --version
