name: ci

on:
  # Trigger the workflow manually
  workflow_dispatch: ~

jobs:
  hello-hpc:
    name: "This is a test"
    runs-on:
      - self-hosted
      - linux
      - hpc
    steps:
      - name: "LS"
        run: |
          echo $(pwd)
          ls -lah
