# SPDX-FileCopyrightText: 2025 European Centre for Medium-Range Weather Forecasts (ECMWF)
# SPDX-License-Identifier: Apache-2.0
name: Build and Test z3fdb

on:
  # Trigger the workflow on push to master or develop, except tag creation
  push:
    branches:
      - 'master'
      - 'develop'
    tags-ignore:
      - '**'

  # Trigger the workflow on pull request (skips draft PRs)
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  # Trigger the workflow manually
  workflow_dispatch: ~

  # Trigger after public PR approved for CI
  pull_request_target:
    types: [labeled]

jobs:
  prepare-deps:
    if: ${{ !github.event.pull_request.draft && (success() || failure()) && (!github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci') }}
    runs-on: [self-hosted, Linux, platform-builder-docker-xl]
    container:
      image: eccr.ecmwf.int/platform-builder/platform-builder:ubuntu-24.04
      credentials:
        username: ${{ secrets.ECMWF_DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.ECMWF_DOCKER_REGISTRY_ACCESS_TOKEN }}
      options: '--user root' # see https://github.com/ecmwf/reusable-workflows/blob/main/.github/workflows/cd-system-package.yml
    steps:
      - name: Get ecbuild
        uses: actions/checkout@v5
        with:
          repository: ecmwf/ecbuild
          ref: develop
          path: ecbuild
      - name: Get stack-dependencies
        uses: actions/checkout@v5
        with:
          repository: ecmwf/stack-dependencies
          ref: master
          path: stack-dependencies-src
          token: ${{ secrets.GH_REPO_READ_TOKEN }}
          submodules: recursive
      - name: Install dependencies
        run: |
          mkdir stack-dependencies-build
          stack-dependencies-src/build.sh --build-path stack-dependencies-build --install-path dependencies  --with-deps libaec,pybind11
      - name: Get eccodes
        uses: actions/checkout@v5
        with:
          repository: ecmwf/eccodes
          ref: develop
          path: eccodes-src
      - name: Install eccodes
        run: |
          mkdir eccodes-build
          cmake \
            -B eccodes-build \
            -S eccodes-src \
            -GNinja \
            -DCMAKE_INSTALL_PREFIX=dependencies \
            -DCMAKE_PREFIX_PATH=dependencies \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DENABLE_MEMFS=ON \
            -DENABLE_AEC=ON
          cmake --build eccodes-build -j -t install
      - name: Get eckit
        uses: actions/checkout@v5
        with:
          repository: ecmwf/eckit
          ref: develop
          path: eckit-src
      - name: Install eckit
        run: |
          mkdir eckit-build
          cmake \
            -B eckit-build \
            -S eckit-src \
            -GNinja \
            -DCMAKE_INSTALL_PREFIX=dependencies \
            -DCMAKE_PREFIX_PATH=dependencies \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build eckit-build -j -t install
      - name: Get metkit
        uses: actions/checkout@v5
        with:
          repository: ecmwf/metkit
          ref: develop
          path: metkit-src
      - name: Install metkit
        run: |
          mkdir metkit-build
          cmake \
            -B metkit-build \
            -S metkit-src \
            -GNinja \
            -DCMAKE_INSTALL_PREFIX=dependencies \
            -DCMAKE_PREFIX_PATH=dependencies \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build metkit-build -j -t install
      - name: Archive with permissions preserved
        run: tar --zstd -cpf files.tar.zst dependencies/ ecbuild/
      - name: Upload dependencies
        uses: actions/upload-artifact@v7
        with:
          name: deps
          path: files.tar.zst
          retention-days: 1
  build-wheels:
    needs: prepare-deps
    if: ${{ !github.event.pull_request.draft && (success() || failure()) && (!github.event.pull_request.head.repo.fork && github.event.action != 'labeled' || github.event.label.name == 'approved-for-ci') }}
    runs-on: [self-hosted, Linux, platform-builder-docker-xl]
    container:
      image: eccr.ecmwf.int/platform-builder/platform-builder:ubuntu-24.04
      credentials:
        username: ${{ secrets.ECMWF_DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.ECMWF_DOCKER_REGISTRY_ACCESS_TOKEN }}
      options: '--user root' # see https://github.com/ecmwf/reusable-workflows/blob/main/.github/workflows/cd-system-package.yml
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14'] # eccodes does not yet support 3.14
      fail-fast: false  # Continue running other versions if one fails

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download dependencies
        uses: actions/download-artifact@v8
        with:
          name: deps
      - name: Extract with zstd
        run: tar --zstd -xpf files.tar.zst
      - name: Get fdb5
        uses: actions/checkout@v5
        with:
          repository: ecmwf/fdb
          path: fdb-src
      - name: Display Python version
        run: python --version
      - name: Install build dependencies
        run: pip install -r fdb-src/requirements.txt
      - name: Build fdb
        run: |
          export PATH=$(pwd)/dependencies/bin:$(pwd)/fdb-build/bin:$PATH
          export ECCODES_HOME=$(pwd)/dependencies
          export FINDLIBS_DISABLE_PACKAGE=yes
          export FINDLIBS_DISABLE_PYTHON=yes
          export ECCODES_PYTHON_USE_FINDLIBS=1
          mkdir fdb-build
          cmake \
            -B fdb-build \
            -S fdb-src \
            -GNinja \
            -DCMAKE_INSTALL_PREFIX=dependencies \
            -DCMAKE_PREFIX_PATH=dependencies \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DENABLE_TOOLS=ON \
            -DENABLE_PYTHON_FDB_INTERFACE=ON \
            -DENABLE_PYTHON_ZARR_INTERFACE=ON
          cmake --build fdb-build -j
          cd fdb-build
          ctest -j $(nproc) --output-on-failure
      - name: Upload wheel
        uses: actions/upload-artifact@v7
        with:
          name: z3fdb-wheel-py${{ matrix.python-version }}
          path: "fdb-build/z3fdb-*.whl"
          retention-days: 10
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
